# inspired by "build GDAL library and to run test with CMake"
# from https://github.com/OSGeo/gdal/blob/master/.github/workflows/cmake_builds.yml

---
name: CMake

on:
    push:
        paths-ignore:
            - 'doc/**'
        branches:
            - main
            - releasebranch_*
    pull_request:
        paths-ignore:
            - 'doc/**'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

env:
    CMAKE_UNITY_BUILD: OFF

permissions:
    contents: read  #  to fetch code (actions/checkout)

jobs:

    build-cmake:
        runs-on: ubuntu-22.04
        env:
            PythonVersion: 3.9
        steps:
            - name: Checkout GRASS
              uses: actions/checkout@v4.1.1
            - name: Set up Python
              uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
              with:
                  python-version: ${{ env.PythonVersion }}
            - name: Install CMake 3.16.0
              run: |
                cd ${GITHUB_WORKSPACE}
                wget https://github.com/Kitware/CMake/releases/download/v3.16.0/cmake-3.16.0-Linux-x86_64.tar.gz
                tar xzf cmake-3.16.0-Linux-x86_64.tar.gz
                echo "CMAKE_DIR=$GITHUB_WORKSPACE/cmake-3.16.0-Linux-x86_64/bin" >> $GITHUB_ENV
                echo "$GITHUB_WORKSPACE/cmake-3.16.0-Linux-x86_64/bin" >> $GITHUB_PATH
            - run: |
                cmake --version
            - name: Install dependencies
              run: |
                sudo apt-get update -y
                sudo apt-get install -y wget git gawk findutils
                xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
                    sudo apt-get install -y --no-install-recommends --no-install-suggests
            - run: python -m pip install ninja
              working-directory: ${{ github.workspace }}
            - name: Print build environment variables
              shell: bash -el {0}
              run: |
                printenv | sort
                gcc --version
                ldd --version
            - name: Create installation directory
              run: |
                mkdir $HOME/install
            - name: Configure
              run: |
                cmake ${CMAKE_OPTIONS} -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -G Ninja \
                  -DCMAKE_INSTALL_PREFIX=$HOME/install -DWITH_NLS=OFF
            - name: Print CMakeCache.txt
              shell: bash -el {0}
              run: |
                cat ${GITHUB_WORKSPACE}/build/CMakeCache.txt
            - name: Build
              run: |
                cmake --build build --verbose -j$(nproc)
            - name: Install
              run: |
                cmake --install $GITHUB_WORKSPACE/build --verbose
            - name: Add the bin directory to PATH
              run: |
                echo "$HOME/install/bin" >> $GITHUB_PATH
            - name: Print installed versions
              if: always()
              run: .github/workflows/print_versions.sh
            - name: Test executing of the grass command
              run: .github/workflows/test_simple.sh
            - name: Run tests
              run: .github/workflows/test_thorough.sh --config .gunittest.cfg
